
# Build Stage

ARG MONGO_DATABASE
ARG MONGOATLAS_URI
ARG SECURITY_URI
ARG CORS_IP
ARG CORS_PORT
ARG PDF1_FILE_NAME
ARG IMAGE_FILE
ARG MERGE_PDF
ARG IMAGE_PATH

#FROM openjdk:8-jdk-alpine as build
FROM alpine:latest as build
RUN apk add maven
COPY . .

ENV MONGO_DATABASE=$MONGO_DATABASE
ENV MONGOATLAS_URI=$MONGOATLAS_URI
ENV CORS_IP=$CORS_IP
ENV CORS_PORT=$CORS_PORT
ENV SECURITY_URI=$SECURITY_URI
ENV EXCEL_FILE_PATH=$EXCEL_FILE_PATH
ENV PDF1_FILE_NAME=$PDF1_FILE_NAME
ENV IMAGE_FILE=$IMAGE_FILE
ENV MERGE_PDF=$MERGE_PDF
ENV IMAGE_PATH=$IMAGE_PATH

ENV AWS_ACCESSKEY=$AWS_ACCESSKEY
ENV AWS_SECRETKEY=$AWS_SECRETKEY
ENV AWS_STATICREGION=$AWS_STATICREGION
ENV AWS_STACKAUTO=$AWS_STACKAUTO
ENV AWS_INSTANCEPROFILE=$AWS_INSTANCEPROFILE
ENV AWS_BUCKETNAME=$AWS_BUCKETNAME
ENV ARCHIVED_DOCSBUCKET=$ARCHIVED_DOCSBUCKET
ENV FUNCTION_NAME=$FUNCTION_NAME

#RUN mvn clean install -q

#Production Stage

FROM openjdk:8-jdk-alpine as prod
WORKDIR /app
RUN mkdir -p data
RUN mkdir -p data/SMASSMAILATTACHMENTS
RUN mkdir -p data/SMASSMAILATTACHMENTS/SCMPDF/
RUN mkdir -p data/SMASSMAILATTACHMENTS/ShipmentImages/
RUN mkdir -p data/SMASSMAILATTACHMENTS/SCMExcel/
RUN mkdir -p data/SMASSMAILATTACHMENTS/SCMPDF/MergedPDF/

COPY --from=build /target /app/target
COPY --from=build /src/main/resources/application.properties /app/src/main/resources/application.properties
RUN chmod -R 777 *


EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/target/SpringBootMongoDB-0.2.4-SMAAS.jar"]


